In [1]:
import numpy as np

****ARRAY OPERATIONS****

*Arithmetic operations*

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 -a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1 // a2

array([0, 0, 0, 0, 0])

In [ ]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
arr2 *2

array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80],
       [82, 84, 86, 88, 90]])

*Broadcasting*

In [3]:
l = [10,20,30,40]
arr = np.array(l)

In [4]:
arr + 10

array([20, 30, 40, 50])

In [ ]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2 = arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

*Deep and Shallow copy*

In [ ]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a[4:6] *10

array([50, 60])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a
b = a.copy()

In [ ]:
b[0] = 99

In [ ]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

*Matrix operations*

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

*Stacking Array*

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting array*

In [ ]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]